version: '3.3'

services: 3/3
  db:
    image: mysql:5.7
    restart: always
    #volumes:
     # - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress
    restart: always:
    #volumes:
     # - ./wp_data:/var/www/html
    ports:
      - "8000:80"
      - "9000:80"
      - "8778:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
   # depends_on:
    #   - db

#volumes:
 #   db_data:
  #  wp_data:
 

